# Generated by Django 2.1 on 2020-06-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_auto_20200613_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_or',
            field=models.BooleanField(default=False),
        ),
    ]
